In [5]:
import numpy as np


# **TASK** **1**
Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
!python --version

Python 3.10.12


In [ ]:
task1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"{task1=}")
task1_1 = np.arange(0,10)
print(f"{task1_1=}")
task1_2 = np.linspace(0,9,num=10, dtype=int)
print(f"{task1_2=}")

task1=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
task1_1=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
task1_2=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# **TASK 2**
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [7]:
task2 = np.zeros((3, 3))
print(task2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **TASK 3**
Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [15]:
task3 = np.random.randint(1, 11, size=(5,5))
print(task3)

[[ 6  4  5  2  9]
 [10  8  4  8  2]
 [ 9  1  6  9  2]
 [ 1  9  8  4  3]
 [ 1  4  8  9 10]]


# **TASK 4**
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.



In [13]:
task4 = np.random.random((4,4))
print(task4)

[[0.36880014 0.37633374 0.55996936 0.13220406]
 [0.82305353 0.05191315 0.39340034 0.95622947]
 [0.50371213 0.23875796 0.91718904 0.59965268]
 [0.60198266 0.14730464 0.11753565 0.64672774]]


# **TASK 5**
Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [18]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print(array1)
print(array2)

[3 1 1 5 8]
[ 4  5  2 10  7]


In [19]:
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print(addition)
print(subtraction)
print(multiplication)

[11 15  3 10  8]
[-7 -3 -1 -4 -4]
[18 54  2 21 12]


# **TASK 6**
Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.



In [21]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
print(vector1)
print(vector2)

scalar = np.dot(vector1, vector2)
print(scalar)


1.9570896757399703


# **TASK 7**
Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [23]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print(matrix1)
print(matrix2)

result = np.dot(matrix1, matrix2)
print("Результат")
print(result)

[[1 3]
 [9 8]]
[[2 1 2]
 [2 2 2]]
Результат
[[ 8  7  8]
 [34 25 34]]


# **TASK 8**
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [28]:
matrix = np.random.randint(1, 11, size=(3,3))
print(matrix)

inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[6 6 5]
 [7 5 4]
 [2 7 4]]
[[-0.2962963   0.40740741 -0.03703704]
 [-0.74074074  0.51851852  0.40740741]
 [ 1.44444444 -1.11111111 -0.44444444]]


# **TASK 9**
Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [30]:
matrix = np.random.randint(1, 11, size=(4,4))
print(matrix)

transposed_matrix= matrix.T
print(transposed_matrix)

[[7 6 9 2]
 [4 1 1 4]
 [5 6 8 7]
 [9 1 2 5]]
[[7 4 5 9]
 [6 1 6 1]
 [9 1 8 2]
 [2 4 7 5]]


# **TASK 10**
Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [45]:
matrix = np.random.randint(1, 11, size=(3,4))
vector = np.random.randint(1, 11, size=(4))

print(matrix)
print(vector)

result = np.dot(matrix, vector)
print("Після множення")
print(result)

[[ 3  3  7  9]
 [10  4  9  2]
 [ 8  4  8  8]]
[ 6 10  9  9]
Після множення
[192 199 232]


# **TASK 11**
Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [48]:
matrix = np.random.random((2,3))
vector = np.random.random((3))

print(matrix)
print(vector)

result = np.dot(matrix, vector)
print("Після множення")
print(result)

[[0.77514697 0.72910502 0.20324913]
 [0.6482954  0.17537232 0.15566857]]
[0.01992192 0.81866633 0.36581566]
Після множення
[[0.01544241 0.59689373 0.07435172]
 [0.01291529 0.14357142 0.056946  ]]


# **TASK 12**
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [47]:
matrix1 = np.random.randint(1, 11, size=(2,2))
matrix2 = np.random.randint(1, 11, size=(2,2))

print(matrix1)
print(matrix2)
result = np.multiply(matrix1, matrix2)
print("Після поелеменого множення")
print(result)

[[8 1]
 [4 5]]
[[ 8  5]
 [ 9 10]]
Після поелеменого множення
[[64  5]
 [36 50]]


# **TASK 13**
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [50]:
matrix1 = np.random.randint(1, 11, size=(2,2))
matrix2 = np.random.randint(1, 11, size=(2,2))

print(matrix1)
print(matrix2)

result = np.dot(matrix1, matrix2)
print("Добуток")
print(result)

[[3 1]
 [7 6]]
[[3 2]
 [5 4]]
Добуток
[[14 10]
 [51 38]]


# **TASK 14**
Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [53]:
matrix = np.random.randint(1, 101, size=(5,5))
print(matrix)

result = np.sum(matrix)
print("Сума всіх елементів")
print(result)

[[61 49  4 57 24]
 [51 90 66 54 19]
 [90 85 73 37 27]
 [52  5  5  3 60]
 [55  3 26  9 42]]
Сума всіх елементів
1047


# **TASK 15**
Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю

In [56]:
matrix1 = np.random.randint(1, 11, size=(4,4))
matrix2 = np.random.randint(1, 11, size=(4,4))

print(matrix1)
print(matrix2)

result = matrix1 - matrix2
print("Різниця")
print(result)



[[ 1  7  3  7]
 [ 6  1  9  7]
 [10  5  9  2]
 [ 1  9  5  9]]
[[ 5  5  6  7]
 [10  2  6  1]
 [ 7  7  7  7]
 [ 1  8  8  2]]
Різниця
[[-4  2 -3  0]
 [-4 -1  3  6]
 [ 3 -2  2 -5]
 [ 0  1 -3  7]]


# **TASK 16**
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



In [59]:
matrix = np.random.random((3,3))

print(matrix)

sum_vector = np.sum(matrix, axis=1, keepdims=True)
print("Сума векторів")
print(sum_vector)

[[0.55301816 0.72919066 0.22155707]
 [0.8429484  0.91438257 0.11063948]
 [0.44734133 0.93821093 0.56104373]]
Сума векторів
[[1.5037659 ]
 [1.86797044]
 [1.94659599]]


# **TASK 17**
Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [60]:
matrix = np.random.randint(1, 11, size=(3, 4))

print(matrix)

squared_matrix = np.square(matrix)
print("√")
print(squared_matrix)

[[ 8  5  1  3]
 [10  2  7  3]
 [ 7  3 10 10]]
√
[[ 64  25   1   9]
 [100   4  49   9]
 [ 49   9 100 100]]


# **TASK 18**
Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.




In [61]:
vector = np.random.randint(1, 51, size=4)

print(vector)

sqrt_vector = np.sqrt(vector)
print("Квадратий корень чисел ")
print(sqrt_vector)

[21 13 14 38]
Квадратий корень чисел 
[4.58257569 3.60555128 3.74165739 6.164414  ]
